# Generated by Django 6.0.3 on 2026-05-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='main_image',
        ),
    ]
